repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0  # this is optional, use `pre-commit autoupdate` to get the latest rev!
    hooks:
    -   id: check-added-large-files
    -   id: check-byte-order-marker
    -   id: check-case-conflict
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-shebang-scripts-are-executable
    -   id: check-toml
    -   id: check-vcs-permalinks
    -   id: check-yaml
    -   id: destroyed-symlinks
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: fix-byte-order-marker
    -   id: mixed-line-ending
    -   id: pretty-format-json
        args: [--autofix]
    -   id: trailing-whitespace
-   repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
    -   id: fmt
    -   id: cargo-check
    -   id: clippy
