[workspace]

resolver = "2"
members = [
    "wastrumentation",
    "wastrumentation_cli",
    "wastrumentation-instr-lib",
    "wasp-compiler",
    "patch-wasi-start-exports",
    "execution-bench",
    "wasm-merge",
]
