[workspace]

resolver = "2"
members = [
    "wastrumentation",
    "wastrumentation-instr-lib",
    "wasp-compiler",
    "wasm-merge",
    "rust-to-wasm-compiler",
]

[workspace.dependencies]
anyhow = "1.0"
wasmtime = "22.0"
indoc = "2"
tempfile = "3.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
wat = "1"
rayon = "1.10"
