[workspace]

resolver = "2"
members = [
    "wastrumentation",
    "wastrumentation-instr-lib",
    "wasp-compiler",
    "wasm-merge",
]

[workspace.dependencies]
anyhow = "1.0"
wasmtime = "22.0"
indoc = "2"
