[workspace]

resolver = "2"
members = [
    "wastrumentation",
    "wastrumentation-cli",
    "wastrumentation-instr-lib",
    "wasp-compiler",
    "patch-wasi-start-exports",
    "integration-tests",
    "wasm-merge",
]
