[package]
name = "wastrumentation-static-analysis"
version = "0.1.0"
edition = "2021"

[dependencies]
wastrumentation = { path = "../wastrumentation" }
# TODO: move this to workspace
wasabi_wasm = { git = "https://github.com/aaronmunsters/wasabi.git", branch = "candidate" }
