[package]
name = "common-language-tests"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
# Languages
rust-to-wasm-compiler = { workspace = true }
wastrumentation-lang-rust = { workspace = true }
wastrumentation-lang-webassembly = { workspace = true }
wastrumentation-lang-assemblyscript = { workspace = true }

# Remaining dependencies
wasmtime = { workspace = true }
wastrumentation = { workspace = true }
tempfile = { workspace = true }
indoc = { workspace = true }
serde = { workspace = true }
