[package]
name = "wastrumentation-instr-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
tempfile = { workspace = true }
bitmask = "0.5.0"
indoc = { workspace = true }

[dev-dependencies]
wasmtime = { workspace = true }
