[package]
name = "wastrumentation-instr-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
paste = "1.0.14"
quote = "1.0.33"
