[package]
name = "assemblyscript-compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
tempfile = { workspace = true }
anyhow = { workspace = true }

[dev-dependencies]
wasmtime = { workspace = true }
