package.name = "rust-wasp-call-stack"
package.version = "0.1.0"
package.edition = "2021"
lib.crate-type = ["cdylib"]
dependencies.wee_alloc = "0.4.5"
profile.release.strip = true
profile.release.lto = true
profile.release.panic = "abort"
profile.dev.panic = "abort"
[workspace]
