(module
    (; ============ TYPES ============ ;)
    (type $i32_i32=>i32
        (func (param i32) (param i32) (; => ;) (result i32)))
    (; ============ FUNCTIONS ============ ;)
    (func $addition (type $i32_i32=>i32)
        (local.get 0)
        (local.get 1)
        (i32.add))
    (func $subtraction (type $i32_i32=>i32)
        (local.get 0)
        (local.get 1)
        (i32.sub))
    (func $multiplication (type $i32_i32=>i32)
        (local.get 0)
        (local.get 1)
        (i32.mul))
    (func $main (param $target i32) (param $a i32) (param $b i32) (result i32)
        (local.get $a)
        (local.get $b)
        (local.get $target)
        (call_indirect $function_table (type $i32_i32=>i32)))
    (; Table with the functions ;)
    (table $function_table funcref
        (elem $addition $subtraction $multiplication))
    (; ============ EXPORTS ============ ;)
    (export "main" (func $main)))
