(module
    (; $main -> $a -> $b -> $c -> $d -> $e ;)
    (func $a (call $b))
    (func $b (call $c))
    (func $c (call $d))
    (func $d (call $e))
    (func $e)
    (func $main (call $a))
    (; ============ EXPORTS ============ ;)
    (export "main" (func $main))
)
