[package]
name = "execution-bench"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
wasi-common = "15.0.1"
wasmtime = "15.0.0"
wasmtime-wasi = "15.0.0"
