[package]
name = "wastrumentation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasabi_wasm = { git = "https://github.com/aaronmunsters/wasabi.git", branch = "candidate" }
wasp-compiler = { path = "../wasp-compiler" }
wastrumentation-instr-lib = { path = "../wastrumentation-instr-lib" }
wasm-merge = { path = "../wasm-merge" }
anyhow = "1.0"

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
wasmer = { git = "https://github.com/XinyuZeng/wasmer.git", branch = "fix_wat" }
wastrumentation = { path = "../wastrumentation" }
wasi-common = "16.0"
wasmtime = "16.0"
wasmtime-wasi = "16.0"
wastrumentation-instr-lib = { path = "../wastrumentation-instr-lib" }
rayon = "1.10"
