[package]
name = "wastrumentation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasabi_wasm = { git = "https://github.com/aaronmunsters/wasabi.git", branch = "candidate" }
wasp-compiler = { path = "../wasp-compiler" }
wastrumentation-instr-lib = { path = "../wastrumentation-instr-lib" }
wasm-merge = { path = "../wasm-merge" }
anyhow = "1.0.75"

[dev-dependencies]
wasmtime = "16.0.0"
