[package]
name = "execution-bench"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
wabt = "0.10.0"
wastrumentation = { path = "../wastrumentation" }
wasi-common = "15.0.1"
wasmtime = "15.0.0"
wasmtime-wasi = "15.0.0"
