[package]
name = "rust-to-wasm-compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
cargo = "0.80.0"
anyhow = "1.0"

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
wat = "1"
wasmtime = { workspace = true }
wastrumentation = { path = "../wastrumentation" }
wastrumentation-instr-lib = { path = "../wastrumentation-instr-lib" }
rayon = "1.10"
