[package]
name = "wasm-merge"
version = "0.1.0"
edition = "2021"

[dependencies]
tempfile = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
wat = { version = "1.239.0" }
wasmtime = { workspace = true }
indoc = { workspace = true }
