name: Rust - Cargo Build, Test, Latest Dependencies & Clippy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  # Reusable job that will be used by CI jobs below
  install_binaryen:
    runs-on: ubuntu-latest
    env:
      binaryen_version: 116
    steps:
      - name: Install Binaryen
        run: &install_binaryen |
          wget https://github.com/WebAssembly/binaryen/releases/download/version_${binaryen_version}/binaryen-version_${binaryen_version}-x86_64-linux.tar.gz
          tar -xzvf binaryen-version_${binaryen_version}-x86_64-linux.tar.gz
          export PATH=$PATH:$(pwd)/binaryen-version_${binaryen_version}/bin

  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: *install_binaryen  # Reuse the install_binaryen anchor
      - run: cargo build --verbose
      - run: cargo test --verbose

  build_test_latest_deps:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - run: *install_binaryen  # Reuse the install_binaryen anchor
      - run: rustup update stable && rustup default stable
      - run: cargo update --verbose
      - run: cargo build --verbose
      - run: cargo test --verbose

  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: *install_binaryen  # Reuse the install_binaryen anchor
      - run: cargo clippy --all-targets --all-features
