name: Rust - Cargo Build, Test & Clippy

on:
  push:
    branches: "*"
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"
  binaryen_version: 116

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Binaryen
        run: |
          mkdir $HOME/binaryen
          wget https://github.com/WebAssembly/binaryen/releases/download/version_${binaryen_version}/binaryen-version_${binaryen_version}-x86_64-linux.tar.gz -O $HOME/binaryen.tar.gz
          tar -xzvf $HOME/binaryen.tar.gz --directory $HOME/binaryen --strip-components=1
          echo "$HOME/binaryen/bin" >> $GITHUB_PATH
          wasm-merge --version # Test if wasm-merge is accessible from shell
      - run: cargo build --verbose
      - run: cargo test --verbose

  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo clippy --all-targets --all-features
