name: Rust - Cargo Build, Test & Clippy

on:
  push:
    branches: "*"
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"
  binaryen_version: 117

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update rustup
        run: rustup update $toolchain && rustup default $toolchain
        shell: bash
      - name: Install Binaryen
        run: |
          mkdir $HOME/binaryen
          wget https://github.com/WebAssembly/binaryen/releases/download/version_${binaryen_version}/binaryen-version_${binaryen_version}-x86_64-linux.tar.gz -O $HOME/binaryen.tar.gz
          tar -xzvf $HOME/binaryen.tar.gz --directory $HOME/binaryen --strip-components=1
          echo "$HOME/binaryen/bin" >> $GITHUB_PATH
      - name: Verify Binaryen installation
        run: wasm-merge --version
      - name: Build all targets with all features
        run: cargo build
        shell: bash
      - name: Install latest nextest release
        uses: taiki-e/install-action@nextest
      - name: Test with latest nextest release
        run: cargo nextest run --all-features

  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update rustup
        run: rustup update $toolchain && rustup default $toolchain
        shell: bash
      - name: Lint (clippy)
        run: cargo clippy --all-features --all-targets
        shell: bash
