name: Rust - Cargo Build, Test & Clippy

on:
  push:
    branches: "*"
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"
  binaryen_version: 119

jobs:
  pre-commit-hooks:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code from GitHub
        uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install pre-commit
        run: |
          pip install pre-commit
          pre-commit --version
      - name: Run pre-commit on all files
        run: |
          pre-commit run --all-files --show-diff-on-failure

  build_test:
    needs: pre-commit-hooks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update rustup
        run: rustup update $toolchain && rustup default $toolchain
      - name: Install wasm as a rust target
        run: rustup target add wasm32-unknown-unknown
        shell: bash
      - name: Install Binaryen
        run: |
          mkdir $HOME/binaryen
          wget https://github.com/WebAssembly/binaryen/releases/download/version_${binaryen_version}/binaryen-version_${binaryen_version}-x86_64-linux.tar.gz -O $HOME/binaryen.tar.gz
          tar -xzvf $HOME/binaryen.tar.gz --directory $HOME/binaryen --strip-components=1
          echo "$HOME/binaryen/bin" >> $GITHUB_PATH
      - name: Verify Binaryen installation
        run: wasm-merge --version
      - name: Build all targets with all features
        run: cargo build
        shell: bash
      - name: Install latest nextest release
        uses: taiki-e/install-action@nextest
      - name: Test with latest nextest release
        run: cargo nextest run --all-features

  clippy_check:
    needs: pre-commit-hooks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update rustup
        run: rustup update $toolchain && rustup default $toolchain
      - name: Install wasm as a rust target
        run: rustup target add wasm32-unknown-unknown
        shell: bash
      - name: Lint (clippy)
        run: cargo clippy --all-features --all-targets
        shell: bash
